name: Send Bluesky Post

on:
    workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: myConsciousness/bluesky-post@v3
        with:
          text: "@shinyakato.dev Test post from Github Actions powered by 'myConsciousness/bluesky-post'."
          media: Dash.png
          media-alt: "My cool photo"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 10
