name: Send Bluesky Post

on:
    workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: myConsciousness/bluesky-post@v4
        with:
          text: "@shinyakato.dev Test post from Github Actions powered by 'myConsciousness/bluesky-post'."
          media: image/Dash.png
          media-alt: "My cool photo"
          langs: "en,ja"
          labels: "fun,sports"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 10
