name: Send Bluesky Post

on:
    workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: myConsciousness/bluesky-post@v5
        with:
          text: "@shinyakato.dev Test post from Github Actions powered by 'myConsciousness/bluesky-post'. #bluesky [test](https://atprotodart.com)"
          langs: "en,ja"
          tags: "test,tag"
          link-preview-url: "https://atprotodart.com"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 10
